import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${inter.className}`} style={{height: '100vh', maxHeight: '100vh', margin: '0px', padding: '0px', backgroundColor: '#F2F3F9'}}>
        {children}
      </body>
    </html>
  )
}
